// فایل words.js - پایگاه داده کلمات پرکاربرد آلمانی
const wordsDatabase = [
    // ==========================================
    // سطح A1 (واژگان پایه و روزمره)
    // ==========================================
    { word: "Mann", article: "der", plural: "die Männer", meaning: "مرد", level: "A1" },
    { word: "Frau", article: "die", plural: "die Frauen", meaning: "زن / خانم", level: "A1" },
    { word: "Kind", article: "das", plural: "die Kinder", meaning: "بچه / کودک", level: "A1" },
    { word: "Tag", article: "der", plural: "die Tage", meaning: "روز", level: "A1" },
    { word: "Nacht", article: "die", plural: "die Nächte", meaning: "شب", level: "A1" },
    { word: "Morgen", article: "der", plural: "die Morgen", meaning: "صبح", level: "A1" },
    { word: "Abend", article: "der", plural: "die Abende", meaning: "عصر / شب", level: "A1" },
    { word: "Zeit", article: "die", plural: "die Zeiten", meaning: "زمان / وقت", level: "A1" },
    { word: "Jahr", article: "das", plural: "die Jahre", meaning: "سال", level: "A1" },
    { word: "Monat", article: "der", plural: "die Monate", meaning: "ماه", level: "A1" },
    { word: "Woche", article: "die", plural: "die Wochen", meaning: "هفته", level: "A1" },
    { word: "Stunde", article: "die", plural: "die Stunden", meaning: "ساعت (مدت زمان)", level: "A1" },
    { word: "Minute", article: "die", plural: "die Minuten", meaning: "دقیقه", level: "A1" },
    { word: "Haus", article: "das", plural: "die Häuser", meaning: "خانه", level: "A1" },
    { word: "Zimmer", article: "das", plural: "die Zimmer", meaning: "اتاق", level: "A1" },
    { word: "Tisch", article: "der", plural: "die Tische", meaning: "میز", level: "A1" },
    { word: "Stuhl", article: "der", plural: "die Stühle", meaning: "صندلی", level: "A1" },
    { word: "Bett", article: "das", plural: "die Betten", meaning: "تخت‌خواب", level: "A1" },
    { word: "Tür", article: "die", plural: "die Türen", meaning: "در", level: "A1" },
    { word: "Fenster", article: "das", plural: "die Fenster", meaning: "پنجره", level: "A1" },
    { word: "Buch", article: "das", plural: "die Bücher", meaning: "کتاب", level: "A1" },
    { word: "Stift", article: "der", plural: "die Stifte", meaning: "خودکار / قلم", level: "A1" },
    { word: "Wasser", article: "das", plural: "die Wässer", meaning: "آب", level: "A1" },
    { word: "Brot", article: "das", plural: "die Brote", meaning: "نان", level: "A1" },
    { word: "Apfel", article: "der", plural: "die Äpfel", meaning: "سیب", level: "A1" },
    { word: "Kaffee", article: "der", plural: "die Kaffees", meaning: "قهوه", level: "A1" },
    { word: "Tee", article: "der", plural: "die Tees", meaning: "چای", level: "A1" },
    { word: "Auto", article: "das", plural: "die Autos", meaning: "ماشین / خودرو", level: "A1" },
    { word: "Bus", article: "der", plural: "die Busse", meaning: "اتوبوس", level: "A1" },
    { word: "Zug", article: "der", plural: "die Züge", meaning: "قطار", level: "A1" },
    { word: "Bahnhof", article: "der", plural: "die Bahnhöfe", meaning: "ایستگاه قطار", level: "A1" },
    { word: "Stadt", article: "die", plural: "die Städte", meaning: "شهر", level: "A1" },
    { word: "Straße", article: "die", plural: "die Straßen", meaning: "خیابان", level: "A1" },
    { word: "Land", article: "das", plural: "die Länder", meaning: "کشور / سرزمین", level: "A1" },
    { word: "Arbeit", article: "die", plural: "die Arbeiten", meaning: "کار / شغل", level: "A1" },
    { word: "Schule", article: "die", plural: "die Schulen", meaning: "مدرسه", level: "A1" },
    { word: "Lehrer", article: "der", plural: "die Lehrer", meaning: "معلم (مرد)", level: "A1" },
    { word: "Schüler", article: "der", plural: "die Schüler", meaning: "دانش‌آموز", level: "A1" },
    { word: "Freund", article: "der", plural: "die Freunde", meaning: "دوست", level: "A1" },
    { word: "Familie", article: "die", plural: "die Familien", meaning: "خانواده", level: "A1" },
    { word: "Vater", article: "der", plural: "die Väter", meaning: "پدر", level: "A1" },
    { word: "Mutter", article: "die", plural: "die Mütter", meaning: "مادر", level: "A1" },
    { word: "Bruder", article: "der", plural: "die Brüder", meaning: "برادر", level: "A1" },
    { word: "Schwester", article: "die", plural: "die Schwestern", meaning: "خواهر", level: "A1" },
    { word: "Sohn", article: "der", plural: "die Söhne", meaning: "پسر (فرزند)", level: "A1" },
    { word: "Tochter", article: "die", plural: "die Töchter", meaning: "دختر (فرزند)", level: "A1" },
    { word: "Geld", article: "das", plural: "die Gelder", meaning: "پول", level: "A1" },
    { word: "Frage", article: "die", plural: "die Fragen", meaning: "سوال", level: "A1" },
    { word: "Name", article: "der", plural: "die Namen", meaning: "نام / اسم", level: "A1" },
    { word: "Wort", article: "das", plural: "die Wörter", meaning: "کلمه / واژه", level: "A1" },
    { word: "Hund", article: "der", plural: "die Hunde", meaning: "سگ", level: "A1" },
    { word: "Katze", article: "die", plural: "die Katzen", meaning: "گربه", level: "A1" },
    { word: "Arzt", article: "der", plural: "die Ärzte", meaning: "پزشک / دکتر", level: "A1" },
    { word: "Problem", article: "das", plural: "die Probleme", meaning: "مشکل", level: "A1" },

    // ==========================================
    // سطح A2 (محیط کار، خرید، سفر و جامعه)
    // ==========================================
    { word: "Schlüssel", article: "der", plural: "die Schlüssel", meaning: "کلید", level: "A2" },
    { word: "Wohnung", article: "die", plural: "die Wohnungen", meaning: "آپارتمان", level: "A2" },
    { word: "Küche", article: "die", plural: "die Küchen", meaning: "آشپزخانه", level: "A2" },
    { word: "Bad", article: "das", plural: "die Bäder", meaning: "حمام", level: "A2" },
    { word: "Platz", article: "der", plural: "die Plätze", meaning: "میدان / جا / مکان", level: "A2" },
    { word: "Markt", article: "der", plural: "die Märkte", meaning: "بازار", level: "A2" },
    { word: "Supermarkt", article: "der", plural: "die Supermärkte", meaning: "سوپرمارکت", level: "A2" },
    { word: "Geschäft", article: "das", plural: "die Geschäfte", meaning: "مغازه / تجارت", level: "A2" },
    { word: "Büro", article: "das", plural: "die Büros", meaning: "دفتر کار / اداره", level: "A2" },
    { word: "Chef", article: "der", plural: "die Chefs", meaning: "رئیس", level: "A2" },
    { word: "Kollege", article: "der", plural: "die Kollegen", meaning: "همکار", level: "A2" },
    { word: "Urlaub", article: "der", plural: "die Urlaube", meaning: "تعطیلات / مرخصی", level: "A2" },
    { word: "Reise", article: "die", plural: "die Reisen", meaning: "سفر / مسافرت", level: "A2" },
    { word: "Flughafen", article: "der", plural: "die Flughäfen", meaning: "فرودگاه", level: "A2" },
    { word: "Flugzeug", article: "das", plural: "die Flugzeuge", meaning: "هواپیما", level: "A2" },
    { word: "Ticket", article: "das", plural: "die Tickets", meaning: "بلیط", level: "A2" },
    { word: "Fahrkarte", article: "die", plural: "die Fahrkarten", meaning: "بلیط (قطار/اتوبوس)", level: "A2" },
    { word: "Hotel", article: "das", plural: "die Hotels", meaning: "هتل", level: "A2" },
    { word: "Gast", article: "der", plural: "die Gäste", meaning: "مهمان", level: "A2" },
    { word: "Einladung", article: "die", plural: "die Einladungen", meaning: "دعوت / دعوت‌نامه", level: "A2" },
    { word: "Party", article: "die", plural: "die Partys", meaning: "مهمانی / جشن", level: "A2" },
    { word: "Geschenk", article: "das", plural: "die Geschenke", meaning: "کادو / هدیه", level: "A2" },
    { word: "Kleidung", article: "die", plural: "die Kleidungen", meaning: "لباس / پوشاک", level: "A2" },
    { word: "Hose", article: "die", plural: "die Hosen", meaning: "شلوار", level: "A2" },
    { word: "Hemd", article: "das", plural: "die Hemden", meaning: "پیراهن مردانه", level: "A2" },
    { word: "Schuh", article: "der", plural: "die Schuhe", meaning: "کفش", level: "A2" },
    { word: "Wetter", article: "das", plural: "die Wetter", meaning: "آب و هوا", level: "A2" },
    { word: "Regen", article: "der", plural: "die Regen", meaning: "باران", level: "A2" },
    { word: "Sonne", article: "die", plural: "die Sonnen", meaning: "خورشید / آفتاب", level: "A2" },
    { word: "Schnee", article: "der", plural: "die Schnee", meaning: "برف", level: "A2" },
    { word: "Wind", article: "der", plural: "die Winde", meaning: "باد", level: "A2" },
    { word: "Gesundheit", article: "die", plural: "die Gesundheiten", meaning: "سلامتی", level: "A2" },
    { word: "Krankenhaus", article: "das", plural: "die Krankenhäuser", meaning: "بیمارستان", level: "A2" },
    { word: "Medizin", article: "die", plural: "die Medizinen", meaning: "دارو / پزشکی", level: "A2" },
    { word: "Schmerz", article: "der", plural: "die Schmerzen", meaning: "درد", level: "A2" },
    { word: "Termin", article: "der", plural: "die Termine", meaning: "قرار ملاقات / وقت", level: "A2" },
    { word: "Preis", article: "der", plural: "die Preise", meaning: "قیمت / جایزه", level: "A2" },
    { word: "Rechnung", article: "die", plural: "die Rechnungen", meaning: "صورت‌حساب / قبض", level: "A2" },
    { word: "Handy", article: "das", plural: "die Handys", meaning: "تلفن همراه / موبایل", level: "A2" },
    { word: "Computer", article: "der", plural: "die Computer", meaning: "کامپیوتر", level: "A2" },
    { word: "Nachricht", article: "die", plural: "die Nachrichten", meaning: "پیام / خبر", level: "A2" },
    { word: "Zeitung", article: "die", plural: "die Zeitungen", meaning: "روزنامه", level: "A2" },
    { word: "Brief", article: "der", plural: "die Briefe", meaning: "نامه", level: "A2" },
    { word: "Übung", article: "die", plural: "die Übungen", meaning: "تمرین", level: "A2" },
    { word: "Sprache", article: "die", plural: "die Sprachen", meaning: "زبان", level: "A2" },
    { word: "Fehler", article: "der", plural: "die Fehler", meaning: "خطا / اشتباه", level: "A2" },
    { word: "Lösung", article: "die", plural: "die Lösungen", meaning: "راه‌حل / جواب", level: "A2" },
    { word: "Wunsch", article: "der", plural: "die Wünsche", meaning: "آرزو / خواسته", level: "A2" },
    { word: "Meinung", article: "die", plural: "die Meinungen", meaning: "نظر / عقیده", level: "A2" },
    { word: "Erfolg", article: "der", plural: "die Erfolge", meaning: "موفقیت", level: "A2" },

    // ==========================================
    // سطح B1 (مفاهیم انتزاعی، جامعه، تحصیل و کار)
    // ==========================================
    { word: "Freiheit", article: "die", plural: "die Freiheiten", meaning: "آزادی", level: "B1" },
    { word: "Geheimnis", article: "das", plural: "die Geheimnisse", meaning: "راز / سر", level: "B1" },
    { word: "Zukunft", article: "die", plural: "die Zukünfte", meaning: "آینده", level: "B1" },
    { word: "Vergangenheit", article: "die", plural: "die Vergangenheiten", meaning: "گذشته", level: "B1" },
    { word: "Gegenwart", article: "die", plural: "die Gegenwarten", meaning: "زمان حال / اکنون", level: "B1" },
    { word: "Gesellschaft", article: "die", plural: "die Gesellschaften", meaning: "جامعه", level: "B1" },
    { word: "Wirtschaft", article: "die", plural: "die Wirtschaften", meaning: "اقتصاد", level: "B1" },
    { word: "Regierung", article: "die", plural: "die Regierungen", meaning: "دولت", level: "B1" },
    { word: "Gesetz", article: "das", plural: "die Gesetze", meaning: "قانون", level: "B1" },
    { word: "Recht", article: "das", plural: "die Rechte", meaning: "حق / حقوق", level: "B1" },
    { word: "Pflicht", article: "die", plural: "die Pflichten", meaning: "وظیفه / تکلیف", level: "B1" },
    { word: "Verantwortung", article: "die", plural: "die Verantwortungen", meaning: "مسئولیت", level: "B1" },
    { word: "Möglichkeit", article: "die", plural: "die Möglichkeiten", meaning: "امکان / فرصت", level: "B1" },
    { word: "Gelegenheit", article: "die", plural: "die Gelegenheiten", meaning: "فرصت / موقعیت", level: "B1" },
    { word: "Entscheidung", article: "die", plural: "die Entscheidungen", meaning: "تصمیم", level: "B1" },
    { word: "Grund", article: "der", plural: "die Gründe", meaning: "دلیل / سبب", level: "B1" },
    { word: "Ursache", article: "die", plural: "die Ursachen", meaning: "علت / ریشه", level: "B1" },
    { word: "Wirkung", article: "die", plural: "die Wirkungen", meaning: "اثر / تأثیر", level: "B1" },
    { word: "Ergebnis", article: "das", plural: "die Ergebnisse", meaning: "نتیجه", level: "B1" },
    { word: "Ziel", article: "das", plural: "die Ziele", meaning: "هدف", level: "B1" },
    { word: "Vorteil", article: "der", plural: "die Vorteile", meaning: "مزیت / فایده", level: "B1" },
    { word: "Nachteil", article: "der", plural: "die Nachteile", meaning: "عیب / نقص / ضرر", level: "B1" },
    { word: "Bedingung", article: "die", plural: "die Bedingungen", meaning: "شرط / وضعیت", level: "B1" },
    { word: "Zustand", article: "der", plural: "die Zustände", meaning: "وضعیت / حالت", level: "B1" },
    { word: "Entwicklung", article: "die", plural: "die Entwicklungen", meaning: "توسعه / پیشرفت", level: "B1" },
    { word: "Erfahrung", article: "die", plural: "die Erfahrungen", meaning: "تجربه", level: "B1" },
    { word: "Verhalten", article: "das", plural: "die Verhalten", meaning: "رفتار", level: "B1" },
    { word: "Verhältnis", article: "das", plural: "die Verhältnisse", meaning: "رابطه / نسبت / شرایط", level: "B1" },
    { word: "Beziehung", article: "die", plural: "die Beziehungen", meaning: "رابطه / ارتباط", level: "B1" },
    { word: "Zusammenhang", article: "der", plural: "die Zusammenhänge", meaning: "ارتباط / زمینه / بافت", level: "B1" },
    { word: "Eindruck", article: "der", plural: "die Eindrücke", meaning: "تأثیر ذهنی / برداشت", level: "B1" },
    { word: "Gedanke", article: "der", plural: "die Gedanken", meaning: "فکر / اندیشه", level: "B1" },
    { word: "Gefühl", article: "das", plural: "die Gefühle", meaning: "احساس", level: "B1" },
    { word: "Interesse", article: "das", plural: "die Interessen", meaning: "علاقه", level: "B1" },
    { word: "Zweifel", article: "der", plural: "die Zweifel", meaning: "شک / تردید", level: "B1" },
    { word: "Angst", article: "die", plural: "die Ängste", meaning: "ترس / دلهره", level: "B1" },
    { word: "Sicherheit", article: "die", plural: "die Sicherheiten", meaning: "امنیت / اطمینان", level: "B1" },
    { word: "Gefahr", article: "die", plural: "die Gefahren", meaning: "خطر", level: "B1" },
    { word: "Risiko", article: "das", plural: "die Risiken", meaning: "ریسک / خطر", level: "B1" },
    { word: "Schutz", article: "der", plural: "die Schütze", meaning: "حفاظت / پناه", level: "B1" },
    { word: "Umwelt", article: "die", plural: "die Umwelten", meaning: "محیط زیست", level: "B1" },
    { word: "Natur", article: "die", plural: "die Naturen", meaning: "طبیعت", level: "B1" },
    { word: "Energie", article: "die", plural: "die Energien", meaning: "انرژی", level: "B1" },
    { word: "Verkehr", article: "der", plural: "die Verkehre", meaning: "ترافیک / رفت و آمد", level: "B1" },
    { word: "System", article: "das", plural: "die Systeme", meaning: "سیستم / نظام", level: "B1" },
    { word: "Bereich", article: "der", plural: "die Bereiche", meaning: "حوزه / بخش / زمینه", level: "B1" },
    { word: "Mitglied", article: "das", plural: "die Mitglieder", meaning: "عضو", level: "B1" },
    { word: "Verein", article: "der", plural: "die Vereine", meaning: "انجمن / باشگاه", level: "B1" },
    { word: "Angebot", article: "das", plural: "die Angebote", meaning: "پیشنهاد / عرضه", level: "B1" },
    { word: "Vertrag", article: "der", plural: "die Verträge", meaning: "قرارداد", level: "B1" },
    { word: "Bewerbung", article: "die", plural: "die Bewerbungen", meaning: "درخواست کار / اپلای", level: "B1" },
    { word: "Ausbildung", article: "die", plural: "die Ausbildungen", meaning: "آموزش حرفه‌ای / کارآموزی", level: "B1" },
    { word: "Studium", article: "das", plural: "die Studien", meaning: "تحصیلات دانشگاهی", level: "B1" },
    { word: "Universität", article: "die", plural: "die Universitäten", meaning: "دانشگاه", level: "B1" },
    { word: "Prüfung", article: "die", plural: "die Prüfungen", meaning: "آزمون / امتحان", level: "B1" },
    { word: "Wissen", article: "das", plural: "die Wissen", meaning: "دانش / آگاهی", level: "B1" },
    { word: "Bedeutung", article: "die", plural: "die Bedeutungen", meaning: "معنی / اهمیت", level: "B1" },
    { word: "Unterschied", article: "der", plural: "die Unterschiede", meaning: "تفاوت / فرق", level: "B1" },
    { word: "Gemeinsamkeit", article: "die", plural: "die Gemeinsamkeiten", meaning: "نقطه اشتراک / شباهت", level: "B1" },
    { word: "Ereignis", article: "das", plural: "die Ereignisse", meaning: "رویداد / اتفاق", level: "B1" },

    // ==========================================
    // سطح B2 (واژگان پیشرفته، علمی، سیاسی و تحلیلی)
    // ==========================================
    { word: "Wettbewerb", article: "der", plural: "die Wettbewerbe", meaning: "رقابت / مسابقه", level: "B2" },
    { word: "Fortschritt", article: "der", plural: "die Fortschritte", meaning: "پیشرفت / ترقی", level: "B2" },
    { word: "Anspruch", article: "der", plural: "die Ansprüche", meaning: "ادعا / مطالبه / حق", level: "B2" },
    { word: "Aufwand", article: "der", plural: "die Aufwände", meaning: "صرف هزینه / زحمت / تلاش", level: "B2" },
    { word: "Begriff", article: "der", plural: "die Begriffe", meaning: "مفهوم / اصطلاح", level: "B2" },
    { word: "Beitrag", article: "der", plural: "die Beiträge", meaning: "سهم / مشارکت / مقاله", level: "B2" },
    { word: "Einfluss", article: "der", plural: "die Einflüsse", meaning: "نفوذ / تأثیر", level: "B2" },
    { word: "Mangel", article: "der", plural: "die Mängel", meaning: "کمبود / نقص", level: "B2" },
    { word: "Umstand", article: "der", plural: "die Umstände", meaning: "شرایط / وضعیت / چگونگی", level: "B2" },
    { word: "Vorgang", article: "der", plural: "die Vorgänge", meaning: "روند / فرآیند / ماجرا", level: "B2" },
    { word: "Widerspruch", article: "der", plural: "die Widersprüche", meaning: "تناقض / مخالفت / اعتراض", level: "B2" },
    { word: "Verlust", article: "der", plural: "die Verluste", meaning: "زیان / ضرر / از دست دادن", level: "B2" },
    { word: "Vorwurf", article: "der", plural: "die Vorwürfe", meaning: "سرزنش / اتهام", level: "B2" },
    { word: "Bedürfnis", article: "das", plural: "die Bedürfnisse", meaning: "نیاز / احتیاج", level: "B2" },
    { word: "Hindernis", article: "das", plural: "die Hindernisse", meaning: "مانع / سد", level: "B2" },
    { word: "Phänomen", article: "das", plural: "die Phänomene", meaning: "پدیده", level: "B2" },
    { word: "Verfahren", article: "das", plural: "die Verfahren", meaning: "روش / رویه قضایی یا اداری", level: "B2" },
    { word: "Vorurteil", article: "das", plural: "die Vorurteile", meaning: "پیش‌داوری / تعصب", level: "B2" },
    { word: "Verlangen", article: "das", plural: "die Verlangen", meaning: "تقاضا / میل شدید / اشتیاق", level: "B2" },
    { word: "Kriterium", article: "das", plural: "die Kriterien", meaning: "معیار / ملاک", level: "B2" },
    { word: "Stadium", article: "das", plural: "die Stadien", meaning: "مرحله / فاز", level: "B2" },
    { word: "Merkmal", article: "das", plural: "die Merkmale", meaning: "ویژگی / مشخصه بارز", level: "B2" },
    { word: "Gleichgewicht", article: "das", plural: "die Gleichgewichte", meaning: "تعادل / توازن", level: "B2" },
    { word: "Konzept", article: "das", plural: "die Konzepte", meaning: "طرح / مفهوم کلی / ایده", level: "B2" },
    { word: "Anforderung", article: "die", plural: "die Anforderungen", meaning: "تقاضا / خواسته / الزام", level: "B2" },
    { word: "Auswirkung", article: "die", plural: "die Auswirkungen", meaning: "پیامد / اثر / بازتاب", level: "B2" },
    { word: "Einschränkung", article: "die", plural: "die Einschränkungen", meaning: "محدودیت / حصر", level: "B2" },
    { word: "Erkenntnis", article: "die", plural: "die Erkenntnisse", meaning: "شناخت / درک / بصیرت", level: "B2" },
    { word: "Fähigkeit", article: "die", plural: "die Fähigkeiten", meaning: "توانایی / قابلیت", level: "B2" },
    { word: "Maßnahme", article: "die", plural: "die Maßnahmen", meaning: "اقدام / تدبیر / گام عملی", level: "B2" },
    { word: "Neigung", article: "die", plural: "die Neigungen", meaning: "تمایل / گرایش / شیب", level: "B2" },
    { word: "Tendenz", article: "die", plural: "die Tendenzen", meaning: "گرایش / روند / تمایل", level: "B2" },
    { word: "Überzeugung", article: "die", plural: "die Überzeugungen", meaning: "عقیده / باور قلبی / متقاعدسازی", level: "B2" },
    { word: "Vereinbarung", article: "die", plural: "die Vereinbarungen", meaning: "توافق / قرار / معاهده", level: "B2" },
    { word: "Verhandlung", article: "die", plural: "die Verhandlungen", meaning: "مذاکره / گفتگو / محاکمه", level: "B2" },
    { word: "Vielfalt", article: "die", plural: "die Vielfalten", meaning: "تنوع / گوناگونی", level: "B2" },
    { word: "Voraussetzung", article: "die", plural: "die Voraussetzungen", meaning: "پیش‌شرط / الزام اولیه", level: "B2" },
    { word: "Zuständigkeit", article: "die", plural: "die Zuständigkeiten", meaning: "صلاحیت / حوزه مسئولیت", level: "B2" },
    { word: "Auseinandersetzung", article: "die", plural: "die Auseinandersetzungen", meaning: "بحث و جدل / درگیری / بررسی دقیق", level: "B2" },
    { word: "Abkommen", article: "das", plural: "die Abkommen", meaning: "تفاهم‌نامه / پیمان", level: "B2" },
    { word: "Behörde", article: "die", plural: "die Behörden", meaning: "اداره دولتی / مقامات رسمی", level: "B2" },
    { word: "Erwerb", article: "der", plural: "die Erwerbe", meaning: "کسب / خرید / اشتغال", level: "B2" },
    { word: "Forderung", article: "die", plural: "die Forderungen", meaning: "مطالبه / درخواست جدی", level: "B2" },
    { word: "Genehmigung", article: "die", plural: "die Genehmigungen", meaning: "مجوز / تأییدیه / اجازه رسمی", level: "B2" },
    { word: "Herkunft", article: "die", plural: "die Herkünfte", meaning: "منشأ / اصالت / زادگاه", level: "B2" },
    { word: "Investition", article: "die", plural: "die Investitionen", meaning: "سرمایه‌گذاری", level: "B2" },
    { word: "Konkurrenz", article: "die", plural: "die Konkurrenzen", meaning: "رقابت / رقیب", level: "B2" },
    { word: "Leistung", article: "die", plural: "die Leistungen", meaning: "عملکرد / دستاورد / کارایی", level: "B2" },
    { word: "Nachfrage", article: "die", plural: "die Nachfragen", meaning: "تقاضا (در اقتصاد) / پرس‌وجو", level: "B2" },
    { word: "Öffentlichkeit", article: "die", plural: "die Öffentlichkeiten", meaning: "عموم مردم / جامعه / افکار عمومی", level: "B2" },
    { word: "Perspektive", article: "die", plural: "die Perspektiven", meaning: "دیدگاه / چشم‌انداز", level: "B2" },
    { word: "Quelle", article: "die", plural: "die Quellen", meaning: "منبع / چشمه", level: "B2" },
    { word: "Ressource", article: "die", plural: "die Ressourcen", meaning: "منبع / ذخیره (طبیعی یا مالی)", level: "B2" },
    { word: "Struktur", article: "die", plural: "die Strukturen", meaning: "ساختار / تشکیلات", level: "B2" },
    { word: "Tatsache", article: "die", plural: "die Tatsachen", meaning: "واقعیت / امر واقع / حقیقت", level: "B2" },
    { word: "Überblick", article: "der", plural: "die Überblicke", meaning: "دید کلی / چشم‌انداز اجمالی", level: "B2" },
    { word: "Verbraucher", article: "der", plural: "die Verbraucher", meaning: "مصرف‌کننده", level: "B2" },
    { word: "Wachstum", article: "das", plural: "die Wachstums", meaning: "رشد / توسعه", level: "B2" },
    { word: "Zusammenarbeit", article: "die", plural: "die Zusammenarbeiten", meaning: "همکاری / مشارکت", level: "B2" },
    { word: "Annahme", article: "die", plural: "die Annahmen", meaning: "فرضیه / پذیرش / گمان", level: "B2" },
    { word: "Betrachtung", article: "die", plural: "die Betrachtungen", meaning: "بررسی / مشاهده / تأمل", level: "B2" },
    { word: "Dimension", article: "die", plural: "die Dimensionen", meaning: "ابعد / بعد / اندازه", level: "B2" },
    { word: "Einschätzung", article: "die", plural: "die Einschätzungen", meaning: "ارزیابی / تخمین / برآورد", level: "B2" },
    { word: "Folge", article: "die", plural: "die Folgen", meaning: "نتیجه / پیامد / قسمت (سریال)", level: "B2" },
    { word: "Grundlage", article: "die", plural: "die Grundlagen", meaning: "پایه / اساس / شالوده", level: "B2" },
    { word: "Herausforderung", article: "die", plural: "die Herausforderungen", meaning: "چالش / مبارزه‌طلبی", level: "B2" },
    { word: "Initiative", article: "die", plural: "die Initiativen", meaning: "ابتکار عمل / پیش‌قدمی", level: "B2" },
    { word: "Kapazität", article: "die", plural: "die Kapazitäten", meaning: "ظرفیت / گنجایش / توانایی", level: "B2" },
    { word: "Leidenschaft", article: "die", plural: "die Leidenschaften", meaning: "اشتیاق شدید / شور و حرارت", level: "B2" },
    { word: "Methode", article: "die", plural: "die Methoden", meaning: "روش / متد / شیوه", level: "B2" },
    { word: "Nutzung", article: "die", plural: "die Nutzungen", meaning: "استفاده / بهره‌برداری", level: "B2" },
    { word: "Orientierung", article: "die", plural: "die Orientierungen", meaning: "جهت‌یابی / گرایش / راهنمایی", level: "B2" },
    { word: "Priorität", article: "die", plural: "die Prioritäten", meaning: "اولویت / حق تقدم", level: "B2" },
    { word: "Qualität", article: "die", plural: "die Qualitäten", meaning: "کیفیت / مرغوبیت", level: "B2" },
    { word: "Relevanz", article: "die", plural: "die Relevanzen", meaning: "ارتباط / اهمیت / موضوعیت", level: "B2" },
    { word: "Strategie", article: "die", plural: "die Strategien", meaning: "استراتژی / راهبرد", level: "B2" },
    { word: "Theorie", article: "die", plural: "die Theorien", meaning: "نظریه / تئوری", level: "B2" },
    { word: "Umsetzung", article: "die", plural: "die Umsetzungen", meaning: "اجرا / پیاده‌سازی / تحقق", level: "B2" },
    { word: "Verfügung", article: "die", plural: "die Verfügungen", meaning: "در اختیار داشتن / دستور / حکم", level: "B2" },
    { word: "Wahrnehmung", article: "die", plural: "die Wahrnehmungen", meaning: "درک / ادراک حسی / برداشت", level: "B2" },
    { word: "Zweck", article: "der", plural: "die Zwecke", meaning: "منظور / مقصود / هدف", level: "B2" },
    { word: "Aufgabe", article: "die", plural: "die Aufgaben", meaning: "وظیفه / تکلیف / کار", level: "B2" },
    { word: "Begrenzung", article: "die", plural: "die Begrenzungen", meaning: "حدود / تعیین مرز / محدود‌سازی", level: "B2" },
    { word: "Chancen", article: "die", plural: "die Chancen", meaning: "شانس‌ها / فرصت‌ها", level: "B2" },
    { word: "Debatte", article: "die", plural: "die Debatten", meaning: "مباحثه / مناظره / گفتگوی جدی", level: "B2" },
    { word: "Empfehlung", article: "die", plural: "die Empfehlungen", meaning: "توصیه / سفارش / پیشنهاد", level: "B2" },
    { word: "Förderung", article: "die", plural: "die Förderungen", meaning: "حمایت / پشتیبانی / استخراج", level: "B2" },
    { word: "Gestaltung", article: "die", plural: "die Gestaltungen", meaning: "طراحی / شکل‌دهی / سازمان‌دهی", level: "B2" },
    { word: "Hoffnung", article: "die", plural: "die Hoffnungen", meaning: "امید / امیدواری", level: "B2" },
    { word: "Integration", article: "die", plural: "die Integrationen", meaning: "ادغام / یکپارچگی / همبستگی", level: "B2" },
    { word: "Kommunikation", article: "die", plural: "die Kommunikationen", meaning: "ارتباطات / مراوده", level: "B2" },
    { word: "Lage", article: "die", plural: "die Lagen", meaning: "موقعیت / وضعیت / محل", level: "B2" },
    { word: "Motivation", article: "die", plural: "die Motivationen", meaning: "انگیزه / اشتیاق درونی", level: "B2" },
    { word: "Norm", article: "die", plural: "die Normen", meaning: "هنجار / استاندارد / قاعده", level: "B2" },
    { word: "Organisation", article: "die", plural: "die Organisationen", meaning: "سازمان / تشکیلات / نظم", level: "B2" },
    { word: "Prinzip", article: "das", plural: "die Prinzipien", meaning: "اصل / قاعده کلی / اصل اخلاقی", level: "B2" },
    { word: "Quittung", article: "die", plural: "die Quittungen", meaning: "رسید / قبض پرداخت", level: "B2" },
    { word: "Reform", article: "die", plural: "die Reformen", meaning: "اصلاحات / بازسازی نظام", level: "B2" },
    { word: "Stellung", article: "die", plural: "die Stellungen", meaning: "موقعیت / جایگاه / موضع", level: "B2" },
    { word: "Tradition", article: "die", plural: "die Traditionen", meaning: "سنت / رسم و رسوم قدیمی", level: "B2" },
    { word: "Unterstützung", article: "die", plural: "die Unterstützungen", meaning: "پشتیبانی / حمایت / کمک", level: "B2" },
    { word: "Verbindung", article: "die", plural: "die Verbindungen", meaning: "ارتباط / اتصال / پیوند", level: "B2" },
    { word: "Wettbewerbsfähigkeit", article: "die", plural: "die Wettbewerbsfähigkeiten", meaning: "توان رقابتی / قابلیت رقابت", level: "B2" },
    { word: "Zufriedenheit", article: "die", plural: "die Zufriedenheiten", meaning: "رضایت / خشنودی", level: "B2" },
    { word: "Ausnahme", article: "die", plural: "die Ausnahmen", meaning: "استثنا", level: "B2" },
    { word: "Bedrohung", article: "die", plural: "die Bedrohungen", meaning: "تهدید / ارعاب", level: "B2" },
    { word: "Charakter", article: "der", plural: "die Charaktere", meaning: "شخصیت / منش / ماهیت", level: "B2" },
    { word: "Distanz", article: "die", plural: "die Distanzen", meaning: "فاصله / مسافت / دوری", level: "B2" },
    { word: "Entwurf", article: "der", plural: "die Entwürfe", meaning: "پیش‌نویس / طرح اولیه / اسکیس", level: "B2" },
    { word: "Funktion", article: "die", plural: "die Funktionen", meaning: "عملکرد / کارکرد / وظیفه", level: "B2" },
    { word: "Grenze", article: "die", plural: "die Grenzen", meaning: "مرز / حد و حدود", level: "B2" },
    { word: "Harmonie", article: "die", plural: "die Harmonien", meaning: "هماهنگی / سازگاری / توازن", level: "B2" },
    { word: "Illusion", article: "die", plural: "die Illusionen", meaning: "توهم / خیال باطل / تصور اشتباه", level: "B2" },
    { word: "Konsequenz", article: "die", plural: "die Konsequenzen", meaning: "عاقبت / پیامد منطقی / ثبات قدم", level: "B2" }
];